<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260410124718 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE time_slot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week VARCHAR(255) NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, garage_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1B3294AC4FFF555 ON time_slot (garage_id)');
        $this->addSql('ALTER TABLE time_slot ADD CONSTRAINT FK_1B3294AC4FFF555 FOREIGN KEY (garage_id) REFERENCES garage (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE time_slot DROP CONSTRAINT FK_1B3294AC4FFF555');
        $this->addSql('DROP TABLE time_slot');
    }
}
