<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414191142 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE car (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, manufacturer VARCHAR(50) NOT NULL, model VARCHAR(50) NOT NULL, license_plate VARCHAR(15) NOT NULL, registration_year SMALLINT DEFAULT NULL, registration_month SMALLINT DEFAULT NULL, mileage INT DEFAULT NULL, is_stored BOOLEAN NOT NULL, color_id INT NOT NULL, client_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_773DE69D7ADA1FB5 ON car (color_id)');
        $this->addSql('CREATE INDEX IDX_773DE69D19EB6921 ON car (client_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_LICENSE_PLATE ON car (license_plate)');
        $this->addSql('CREATE TABLE client (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, last_name VARCHAR(50) NOT NULL, first_name VARCHAR(50) NOT NULL, email VARCHAR(180) DEFAULT NULL, phone_number VARCHAR(20) NOT NULL, is_client_called_back BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE color (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, hex_code VARCHAR(7) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE employee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, last_name VARCHAR(50) NOT NULL, first_name VARCHAR(50) NOT NULL, birth_date DATE NOT NULL, start_date DATE DEFAULT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE garage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, siret_number VARCHAR(14) NOT NULL, name VARCHAR(50) NOT NULL, street VARCHAR(255) NOT NULL, city VARCHAR(100) NOT NULL, zip_code VARCHAR(5) NOT NULL, phone VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SIRET_NUMBER ON garage (siret_number)');
        $this->addSql('CREATE TABLE garage_employee (garage_id INT NOT NULL, employee_id INT NOT NULL, PRIMARY KEY (garage_id, employee_id))');
        $this->addSql('CREATE INDEX IDX_AD16A609C4FFF555 ON garage_employee (garage_id)');
        $this->addSql('CREATE INDEX IDX_AD16A6098C03F15C ON garage_employee (employee_id)');
        $this->addSql('CREATE TABLE mechanic (pin VARCHAR(255) NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE owner (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, last_name VARCHAR(50) NOT NULL, first_name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON owner (email)');
        $this->addSql('CREATE TABLE owner_garage (owner_id INT NOT NULL, garage_id INT NOT NULL, PRIMARY KEY (owner_id, garage_id))');
        $this->addSql('CREATE INDEX IDX_3ADC4D557E3C61F9 ON owner_garage (owner_id)');
        $this->addSql('CREATE INDEX IDX_3ADC4D55C4FFF555 ON owner_garage (garage_id)');
        $this->addSql('CREATE TABLE receptionist (email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_RECEPTIONIST_EMAIL ON receptionist (email)');
        $this->addSql('CREATE TABLE time_slot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week VARCHAR(255) NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, garage_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1B3294AC4FFF555 ON time_slot (garage_id)');
        $this->addSql('ALTER TABLE car ADD CONSTRAINT FK_773DE69D7ADA1FB5 FOREIGN KEY (color_id) REFERENCES color (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE car ADD CONSTRAINT FK_773DE69D19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE garage_employee ADD CONSTRAINT FK_AD16A609C4FFF555 FOREIGN KEY (garage_id) REFERENCES garage (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE garage_employee ADD CONSTRAINT FK_AD16A6098C03F15C FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mechanic ADD CONSTRAINT FK_7137DE79BF396750 FOREIGN KEY (id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE owner_garage ADD CONSTRAINT FK_3ADC4D557E3C61F9 FOREIGN KEY (owner_id) REFERENCES owner (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE owner_garage ADD CONSTRAINT FK_3ADC4D55C4FFF555 FOREIGN KEY (garage_id) REFERENCES garage (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE receptionist ADD CONSTRAINT FK_F168ACCFBF396750 FOREIGN KEY (id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE time_slot ADD CONSTRAINT FK_1B3294AC4FFF555 FOREIGN KEY (garage_id) REFERENCES garage (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE car DROP CONSTRAINT FK_773DE69D7ADA1FB5');
        $this->addSql('ALTER TABLE car DROP CONSTRAINT FK_773DE69D19EB6921');
        $this->addSql('ALTER TABLE garage_employee DROP CONSTRAINT FK_AD16A609C4FFF555');
        $this->addSql('ALTER TABLE garage_employee DROP CONSTRAINT FK_AD16A6098C03F15C');
        $this->addSql('ALTER TABLE mechanic DROP CONSTRAINT FK_7137DE79BF396750');
        $this->addSql('ALTER TABLE owner_garage DROP CONSTRAINT FK_3ADC4D557E3C61F9');
        $this->addSql('ALTER TABLE owner_garage DROP CONSTRAINT FK_3ADC4D55C4FFF555');
        $this->addSql('ALTER TABLE receptionist DROP CONSTRAINT FK_F168ACCFBF396750');
        $this->addSql('ALTER TABLE time_slot DROP CONSTRAINT FK_1B3294AC4FFF555');
        $this->addSql('DROP TABLE car');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE color');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE garage');
        $this->addSql('DROP TABLE garage_employee');
        $this->addSql('DROP TABLE mechanic');
        $this->addSql('DROP TABLE owner');
        $this->addSql('DROP TABLE owner_garage');
        $this->addSql('DROP TABLE receptionist');
        $this->addSql('DROP TABLE time_slot');
    }
}
