<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260410152436 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE employee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, last_name VARCHAR(50) NOT NULL, first_name VARCHAR(50) NOT NULL, birth_date DATE NOT NULL, start_date DATE DEFAULT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE garage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, siret_number VARCHAR(14) NOT NULL, name VARCHAR(50) NOT NULL, street VARCHAR(255) NOT NULL, city VARCHAR(100) NOT NULL, zip_code VARCHAR(5) NOT NULL, phone VARCHAR(20) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SIRET_NUMBER ON garage (siret_number)');
        $this->addSql('CREATE TABLE mechanic (pin VARCHAR(255) NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE owner (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, last_name VARCHAR(50) NOT NULL, first_name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON owner (email)');
        $this->addSql('CREATE TABLE owner_garage (owner_id INT NOT NULL, garage_id INT NOT NULL, PRIMARY KEY (owner_id, garage_id))');
        $this->addSql('CREATE INDEX IDX_3ADC4D557E3C61F9 ON owner_garage (owner_id)');
        $this->addSql('CREATE INDEX IDX_3ADC4D55C4FFF555 ON owner_garage (garage_id)');
        $this->addSql('CREATE TABLE receptionist (email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_RECEPTIONIST_EMAIL ON receptionist (email)');
        $this->addSql('CREATE TABLE time_slot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week VARCHAR(255) NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, garage_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1B3294AC4FFF555 ON time_slot (garage_id)');
        $this->addSql('ALTER TABLE mechanic ADD CONSTRAINT FK_7137DE79BF396750 FOREIGN KEY (id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE owner_garage ADD CONSTRAINT FK_3ADC4D557E3C61F9 FOREIGN KEY (owner_id) REFERENCES owner (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE owner_garage ADD CONSTRAINT FK_3ADC4D55C4FFF555 FOREIGN KEY (garage_id) REFERENCES garage (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE receptionist ADD CONSTRAINT FK_F168ACCFBF396750 FOREIGN KEY (id) REFERENCES employee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE time_slot ADD CONSTRAINT FK_1B3294AC4FFF555 FOREIGN KEY (garage_id) REFERENCES garage (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE mechanic DROP CONSTRAINT FK_7137DE79BF396750');
        $this->addSql('ALTER TABLE owner_garage DROP CONSTRAINT FK_3ADC4D557E3C61F9');
        $this->addSql('ALTER TABLE owner_garage DROP CONSTRAINT FK_3ADC4D55C4FFF555');
        $this->addSql('ALTER TABLE receptionist DROP CONSTRAINT FK_F168ACCFBF396750');
        $this->addSql('ALTER TABLE time_slot DROP CONSTRAINT FK_1B3294AC4FFF555');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE garage');
        $this->addSql('DROP TABLE mechanic');
        $this->addSql('DROP TABLE owner');
        $this->addSql('DROP TABLE owner_garage');
        $this->addSql('DROP TABLE receptionist');
        $this->addSql('DROP TABLE time_slot');
    }
}
