<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260416131331 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE intervention_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity SMALLINT DEFAULT 1 NOT NULL, intervention_id INT NOT NULL, service_task_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5DC1C3E78EAE3863 ON intervention_task (intervention_id)');
        $this->addSql('CREATE INDEX IDX_5DC1C3E74232531A ON intervention_task (service_task_id)');
        $this->addSql('CREATE TABLE service_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, unit_price NUMERIC(10, 2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE intervention_task ADD CONSTRAINT FK_5DC1C3E78EAE3863 FOREIGN KEY (intervention_id) REFERENCES intervention (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE intervention_task ADD CONSTRAINT FK_5DC1C3E74232531A FOREIGN KEY (service_task_id) REFERENCES service_task (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE intervention_task DROP CONSTRAINT FK_5DC1C3E78EAE3863');
        $this->addSql('ALTER TABLE intervention_task DROP CONSTRAINT FK_5DC1C3E74232531A');
        $this->addSql('DROP TABLE intervention_task');
        $this->addSql('DROP TABLE service_task');
    }
}
