<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414135128 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE car (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, manufacturer VARCHAR(50) NOT NULL, model VARCHAR(50) NOT NULL, license_plate VARCHAR(15) NOT NULL, registration_year SMALLINT DEFAULT NULL, registration_month SMALLINT DEFAULT NULL, mileage INT DEFAULT NULL, is_stored BOOLEAN NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE car');
    }
}
