<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520093148 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE manufacturer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_MANUFACTURER_NAME ON manufacturer (name)');
        $this->addSql('ALTER TABLE car ADD manufacturer_id INT NOT NULL');
        $this->addSql('ALTER TABLE car DROP manufacturer');
        $this->addSql('ALTER TABLE car ADD CONSTRAINT FK_773DE69DA23B42D FOREIGN KEY (manufacturer_id) REFERENCES manufacturer (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_773DE69DA23B42D ON car (manufacturer_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE manufacturer');
        $this->addSql('ALTER TABLE car DROP CONSTRAINT FK_773DE69DA23B42D');
        $this->addSql('DROP INDEX IDX_773DE69DA23B42D');
        $this->addSql('ALTER TABLE car ADD manufacturer VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE car DROP manufacturer_id');
    }
}
