<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414164512 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE color (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, hex_code VARCHAR(7) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE car ADD color_id INT NOT NULL');
        $this->addSql('ALTER TABLE car ADD CONSTRAINT FK_773DE69D7ADA1FB5 FOREIGN KEY (color_id) REFERENCES color (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_773DE69D7ADA1FB5 ON car (color_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_LICENSE_PLATE ON car (license_plate)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE color');
        $this->addSql('ALTER TABLE car DROP CONSTRAINT FK_773DE69D7ADA1FB5');
        $this->addSql('DROP INDEX IDX_773DE69D7ADA1FB5');
        $this->addSql('DROP INDEX UNIQ_LICENSE_PLATE');
        $this->addSql('ALTER TABLE car DROP color_id');
    }
}
